"""empty message

Revision ID: 1cdfead2401e
Revises: 
Create Date: 2020-07-07 20:24:43.811376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cdfead2401e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('posts')
    op.drop_table('tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('tag_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name='tags_post_id_fkey'),
    sa.PrimaryKeyConstraint('tag_id', name='tags_pkey')
    )
    op.create_table('posts',
    sa.Column('post_id', sa.INTEGER(), server_default=sa.text("nextval('posts_post_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('photo', sa.VARCHAR(length=1000000), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('post_id', name='posts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('comments',
    sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(length=1000), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.post_id'], name='comments_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='comments_user_id_fkey'),
    sa.PrimaryKeyConstraint('comment_id', name='comments_pkey')
    )
    # ### end Alembic commands ###
